name: almuandes_billing_system
description: "ArabicEngineerBillingSystem App"
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  neuss_utils:
    git:
      url: https://github.com/abuzeit/neuss_utils.git
      ref: ^1.0.9


  get: ^4.7.2
  get_storage: ^2.1.1

  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_analytics: ^11.2.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  uuid: ^4.4.2

  #  awesome_notifications: ^0.7.4+1
  #  awesome_notifications_fcm: ^0.7.4+1
  fcm_config: ^3.5.3
  timezone: ^0.10.0


  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1
  flare_flutter: ^3.0.2
  pin_code_fields: ^8.0.1
  loading_indicator: ^3.1.1
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  im_stepper: ^1.0.1+1


  ready_extensions: ^1.3.2
  dart_extensions: ^2.2.4
  date_only_field: ^0.0.14

  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5


  carousel_slider: ^5.0.0
  video_player:
  app_settings: ^5.1.1
  synchronized: ^3.1.0+1
#  move_to_background: ^1.0.2
  convex_bottom_bar: ^3.2.0
  geolocator: ^10.1.0
  google_api_headers: ^4.2.0
  google_maps_flutter: ^2.9.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  location: ^7.0.0
  flutter_osm_plugin: ^1.2.0
  flutter_map_marker_popup: ^7.0.0

  flutter_form_builder: 9.4.0
  form_builder_validators: ^11.0.0
  form_builder_extra_fields: 10.2.0

  flutter_sliding_box: ^1.1.5
  flutter_map_location_marker: ^9.0.0
  #  flutter_map_marker_cluster: ^1.3.6

  location_picker_flutter_map: ^3.1.0






dependency_overrides:
#  neuss_utils:
#    path: D:/elshab7/Work/Flutter_Work/ABUZEIT/Base_App/neuss_utils

  win32: ^5.5.4
  http: ^1.2.2
  web: ^1.0.0
  ffi: ^2.1.3
  intl: ^0.19.0
  device_info_plus: ^10.1.2
  flex_color_scheme: ^8.1.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  dropdown_search: ^5.0.6
  package_info_plus: ^8.0.2
  file_selector_linux: ^0.9.2+1
  uuid: ^4.4.2
  js: ^0.7.1
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  infinite_scroll_pagination: ^4.0.0
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  firebase_core: ^3.3.0

  flutter_form_builder: 9.4.0
  form_builder_validators: ^11.0.0
  form_builder_extra_fields: 10.2.0
  google_api_headers: ^4.2.0
  location: ^7.0.0
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  flutter_map_marker_popup: ^7.0.0

  logger: ^2.0.0


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

#  flutter pub get
#  dart run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_icon.png

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/app_icon.png
  #  image_dark: assets/images/ic_launcher.png

  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/app_icon5.png

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
