///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String acheivementSelectedTabIcon =
      'assets/images/acheivement_selected_tab_icon.png';
  static const String appIcon = 'assets/images/app_icon.png';
  static const String appIcon100 = 'assets/images/app_icon_100.png';
  static const String appIcon45 = 'assets/images/app_icon_45.png';
  static const String board1 = 'assets/images/board1.png';
  static const String board2 = 'assets/images/board2.png';
  static const String board3 = 'assets/images/board3.png';
  static const String board4 = 'assets/images/board4.mp4';
  static const String darkPageBg = 'assets/images/dark_page_bg.png';
  static const String donationImageBg = 'assets/images/donation_image_bg.png';
  static const String femaleGreenAvatarIcon =
      'assets/images/female_green_avatar_icon.png';
  static const String fuel = 'assets/images/fuel.jpeg';
  static const String gift = 'assets/images/gift.png';
  static const String location1 = 'assets/images/location1.png';
  static const String location2 = 'assets/images/location2.png';
  static const String locationIcon = 'assets/images/location_icon.png';
  static const String locationPin = 'assets/images/location_pin.webp';
  static const String maleGreenAvatarIcon =
      'assets/images/male_green_avatar_icon.png';
  static const String neuss = 'assets/images/neuss.png';
  static const String noConnection = 'assets/images/no_connection.png';
  static const String orderLpg = 'assets/images/order_lpg.jpg';
  static const String otp = 'assets/images/otp.flr';
  static const String pageBg = 'assets/images/page_bg.png';
  static const String pin = 'assets/images/pin.png';
  static const String pin1 = 'assets/images/pin_1.png';
  static const String pin2 = 'assets/images/pin_2.png';
  static const String pin3 = 'assets/images/pin_3.png';
  static const String pin4 = 'assets/images/pin_4.png';
  static const String pin5 = 'assets/images/pin_5.png';
  static const String pinFrom = 'assets/images/pin_from.png';
  static const String pinTo = 'assets/images/pin_to.png';
  static const String serverErrorIcon = 'assets/images/server_error_icon.png';
  static const String vehicle1 = 'assets/images/vehicle1.jpg';
  static const String vehicle2 = 'assets/images/vehicle2.png';
  static const String wallet = 'assets/images/wallet.jpeg';
  static const String whatsappIcon = 'assets/images/whatsapp_icon.svg';
}
